import type { NetworkUser, CheckIn } from "@/types";

export const interestOptions = [
  { id: "coffee", emoji: "☕", label: "Coffee Chats" },
  { id: "running", emoji: "🏃", label: "Running" },
  { id: "hiking", emoji: "🥾", label: "Hiking" },
  { id: "foodie", emoji: "🍜", label: "Foodie" },
  { id: "happy-hour", emoji: "🍻", label: "Happy Hour" },
  { id: "board-games", emoji: "🎲", label: "Board Games" },
  { id: "sports", emoji: "⚽", label: "Sports Fan" },
  { id: "photography", emoji: "📸", label: "Photography" },
  { id: "yoga", emoji: "🧘", label: "Yoga & Wellness" },
  { id: "music", emoji: "🎵", label: "Live Music" },
  { id: "reading", emoji: "📚", label: "Book Club" },
  { id: "tech-talks", emoji: "💻", label: "Tech Talks" },
  { id: "cooking", emoji: "👨‍🍳", label: "Cooking" },
  { id: "cycling", emoji: "🚴", label: "Cycling" },
  { id: "volunteering", emoji: "🤝", label: "Volunteering" },
];

export const amazonSites = [
  { code: "SEA", name: "Seattle, WA (HQ)", lat: 47.6062, lng: -122.3321 },
  { code: "YVR14", name: "Vancouver, Canada", lat: 49.2827, lng: -123.1207 },
  { code: "HYZ1", name: "Oakville, Canada", lat: 43.4675, lng: -79.6877 },
  { code: "DXT8", name: "Stoney Creek, Canada", lat: 43.2173, lng: -79.7164 },
  { code: "HYM2", name: "Cambridge, Canada", lat: 43.3616, lng: -80.3144 },
  { code: "DTY7", name: "Kitchener, Canada", lat: 43.4516, lng: -80.4925 },
  { code: "BNA", name: "Nashville, TN", lat: 36.1627, lng: -86.7816 },
  { code: "DFW", name: "Dallas, TX", lat: 32.7767, lng: -96.797 },
  { code: "AUS", name: "Austin, TX", lat: 30.2672, lng: -97.7431 },
  { code: "WAS19", name: "Arlington, VA", lat: 38.8816, lng: -77.091 },
  { code: "JFK", name: "New York, NY", lat: 40.7128, lng: -74.006 },
  { code: "SFO", name: "San Francisco, CA", lat: 37.7749, lng: -122.4194 },
];

const avatarColors = [
  "#FF6B35", "#7B61FF", "#2ECC71", "#E91E63", "#00BCD4",
  "#FF9900", "#FFC107", "#9C27B0", "#009688", "#3F51B5",
];

export const mockNetworkUsers: NetworkUser[] = [
  {
    id: "nu1",
    amazonAlias: "janbez",
    displayName: "Jan Bezos-Garcia",
    title: "Sr. Program Manager",
    team: "Ops Excellence",
    level: "L6",
    siteCode: "YVR14",
    siteName: "Vancouver, Canada",
    interests: ["coffee", "hiking", "foodie", "tech-talks"],
    connectionMode: "BOTH",
    avatarColor: avatarColors[0],
    checkedIn: true,
    arrivalDate: "2026-07-12",
    departureDate: "2026-07-18",
  },
  {
    id: "nu2",
    amazonAlias: "priyam",
    displayName: "Priya Mukherjee",
    title: "Business Analyst",
    team: "Supply Chain",
    level: "L5",
    siteCode: "YVR14",
    siteName: "Vancouver, Canada",
    interests: ["yoga", "foodie", "photography", "coffee"],
    connectionMode: "IN_PERSON",
    avatarColor: avatarColors[1],
    checkedIn: true,
    arrivalDate: "2026-07-13",
    departureDate: "2026-07-16",
  },
  {
    id: "nu3",
    amazonAlias: "mikech",
    displayName: "Mike Chen",
    title: "Software Dev Engineer",
    team: "Robotics",
    level: "L5",
    siteCode: "YVR14",
    siteName: "Vancouver, Canada",
    interests: ["board-games", "happy-hour", "cycling", "tech-talks"],
    connectionMode: "BOTH",
    avatarColor: avatarColors[2],
    checkedIn: true,
    arrivalDate: "2026-07-10",
    departureDate: "2026-07-17",
  },
  {
    id: "nu4",
    amazonAlias: "sarahk",
    displayName: "Sarah Kim",
    title: "ER Manager",
    team: "PXT Corporate ER",
    level: "L6",
    siteCode: "YVR14",
    siteName: "Vancouver, Canada",
    interests: ["running", "coffee", "happy-hour", "volunteering"],
    connectionMode: "IN_PERSON",
    avatarColor: avatarColors[3],
    checkedIn: true,
    arrivalDate: "2026-07-14",
    departureDate: "2026-07-20",
  },
  {
    id: "nu5",
    amazonAlias: "devpat",
    displayName: "Dev Patel",
    title: "Operations Manager",
    team: "Last Mile",
    level: "L6",
    siteCode: "YVR14",
    siteName: "Vancouver, Canada",
    interests: ["sports", "foodie", "happy-hour", "music"],
    connectionMode: "BOTH",
    avatarColor: avatarColors[4],
    checkedIn: true,
    arrivalDate: "2026-07-11",
    departureDate: "2026-07-15",
  },
  {
    id: "nu6",
    amazonAlias: "lisawu",
    displayName: "Lisa Wu",
    title: "Data Scientist",
    team: "Forecasting",
    level: "L5",
    siteCode: "SEA",
    siteName: "Seattle, WA (HQ)",
    interests: ["hiking", "coffee", "reading", "yoga"],
    connectionMode: "BOTH",
    avatarColor: avatarColors[5],
    checkedIn: true,
    arrivalDate: "2026-07-13",
    departureDate: "2026-07-19",
  },
  {
    id: "nu7",
    amazonAlias: "jamesm",
    displayName: "James Moreno",
    title: "Area Manager",
    team: "Fulfillment Ops",
    level: "L5",
    siteCode: "SEA",
    siteName: "Seattle, WA (HQ)",
    interests: ["sports", "happy-hour", "cooking", "cycling"],
    connectionMode: "IN_PERSON",
    avatarColor: avatarColors[6],
    checkedIn: true,
    arrivalDate: "2026-07-12",
    departureDate: "2026-07-16",
  },
  {
    id: "nu8",
    amazonAlias: "amandac",
    displayName: "Amanda Clarke",
    title: "Sr. HR Partner",
    team: "PXT Field",
    level: "L6",
    siteCode: "SEA",
    siteName: "Seattle, WA (HQ)",
    interests: ["coffee", "volunteering", "reading", "yoga"],
    connectionMode: "VIRTUAL",
    avatarColor: avatarColors[7],
    checkedIn: true,
    arrivalDate: "2026-07-14",
    departureDate: "2026-07-18",
  },
  {
    id: "nu9",
    amazonAlias: "tomr",
    displayName: "Tom Ramirez",
    title: "Solutions Architect",
    team: "AWS ProServ",
    level: "L6",
    siteCode: "WAS19",
    siteName: "Arlington, VA",
    interests: ["tech-talks", "happy-hour", "running", "photography"],
    connectionMode: "BOTH",
    avatarColor: avatarColors[8],
    checkedIn: true,
    arrivalDate: "2026-07-10",
    departureDate: "2026-07-20",
  },
  {
    id: "nu10",
    amazonAlias: "ninaj",
    displayName: "Nina Johnson",
    title: "Program Manager",
    team: "DEI Ops",
    level: "L5",
    siteCode: "WAS19",
    siteName: "Arlington, VA",
    interests: ["volunteering", "foodie", "music", "coffee"],
    connectionMode: "BOTH",
    avatarColor: avatarColors[9],
    checkedIn: true,
    arrivalDate: "2026-07-13",
    departureDate: "2026-07-17",
  },
  {
    id: "nu11",
    amazonAlias: "ryanb",
    displayName: "Ryan Brooks",
    title: "Finance Manager",
    team: "Corp FP&A",
    level: "L6",
    siteCode: "BNA",
    siteName: "Nashville, TN",
    interests: ["music", "happy-hour", "sports", "cooking"],
    connectionMode: "IN_PERSON",
    avatarColor: avatarColors[0],
    checkedIn: true,
    arrivalDate: "2026-07-12",
    departureDate: "2026-07-15",
  },
  {
    id: "nu12",
    amazonAlias: "emilyt",
    displayName: "Emily Torres",
    title: "UX Designer",
    team: "Consumer Design",
    level: "L5",
    siteCode: "BNA",
    siteName: "Nashville, TN",
    interests: ["photography", "foodie", "coffee", "hiking"],
    connectionMode: "BOTH",
    avatarColor: avatarColors[3],
    checkedIn: true,
    arrivalDate: "2026-07-14",
    departureDate: "2026-07-19",
  },
];

export function getUsersAtSite(siteCode: string): NetworkUser[] {
  return mockNetworkUsers.filter(
    (u) => u.siteCode === siteCode && u.checkedIn
  );
}

export function getSharedInterests(
  userInterests: string[],
  otherInterests: string[]
): string[] {
  return userInterests.filter((i) => otherInterests.includes(i));
}

export function getInterestEmoji(interestId: string): string {
  const found = interestOptions.find((i) => i.id === interestId);
  return found?.emoji || "✨";
}

export function getInterestLabel(interestId: string): string {
  const found = interestOptions.find((i) => i.id === interestId);
  return found?.label || interestId;
}
